name: minix
description: A powerful, lightweight state management and dependency injection solution for Flutter applications with reactive programming capabilities.
version: 1.0.0
homepage: https://github.com/jaiprakash274/minix
repository: https://github.com/jaiprakash274/minix
issue_tracker: https://github.com/jaiprakash274/minix/issues
documentation: https://github.com/jaiprakash274/minix/latest/

topics:
  - state-management
  - dependency-injection
  - reactive-programming
  - flutter
  - observables

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is Flutter-specific.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages

# An image asset can refer to one or more resolution-variant files:
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic




